version: "3.4"
services:
  mssql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    user: root
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=EShopPWD!"
    ports:
      - "1433:1433"
    volumes:
      - asql_eshop_data:/var/opt/mssql/data
volumes:
  asql_eshop_data:
